apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: imageprocessor
  labels:
    deployment: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: celery-worker
  template:
    metadata:
      labels:
        pod: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: claudeforlife/imageprocessor:latest
          workingDir: /opt/app/imageProcessor/
          # command: ["bash", "-c", celery -A imageProcessor worker -l info --concurrency 2"]
          command: ["bash", "-c", "celery -A imageProcessor worker -l debug"]

          env:
            - name: SECRET_KEY
              value: "my-secret-key"

            - name: POSTGRES_NAME
              value: postgres

            - name: REDIS_SERVICE_HOST
              value: redis
  
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password