apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minikube-ingress
spec:
  rules:
  - host: minikube.local
    http:
      paths:
      - path: /admin/
        backend:
          serviceName: kubernetes-django-service
          servicePort: 8020
      - path: /
        backend:
          serviceName: kubernetes-django-service
          servicePort: 8020
