# Generated by Django 3.1.7 on 2021-03-24 15:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProcessorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/imageProcessorApp/photos'), upload_to='')),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_verified', models.BooleanField(default=False)),
                ('image_rejected', models.BooleanField()),
            ],
        ),
    ]
