# Generated by Django 3.1.7 on 2021-03-24 16:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessorApp', '0002_auto_20210324_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessormodel',
            name='image_rejected',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='imageprocessormodel',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Users/ebaneck/Desktop/photos'), upload_to=''),
        ),
    ]
