# Generated by Django 3.1.7 on 2021-03-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessorApp', '0003_auto_20210324_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessormodel',
            name='image_rejected',
            field=models.BooleanField(null=True),
        ),
    ]
